apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-api
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
